import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
<<<<<<< HEAD
=======
import Provider from "@/lib/providers/provider";
import { Toaster } from "@/components/ui/sonner";
>>>>>>> 7f14cc3b6acbbdf51ffc200d3d8d27084e350e05

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IW 2K26",
  description: "Generated by create next app",
};

<<<<<<< HEAD
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <TooltipProvider>{children}</TooltipProvider>
=======
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange >
          <TooltipProvider>
            <Provider>
              {children}
              <Toaster />
            </Provider>
          </TooltipProvider>
>>>>>>> 7f14cc3b6acbbdf51ffc200d3d8d27084e350e05
        </ThemeProvider>
      </body>
    </html>
  );
}
